# Generated by Django 5.0.4 on 2025-10-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_order_admin_log_order_customer_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='service_types/'),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='star',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
