# Generated by Django 5.0.4 on 2025-11-09 05:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0009_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hours_peak', models.BooleanField(default=False)),
                ('customer_history_score', models.PositiveIntegerField(default=0)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('proposed_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accepted_status', models.BooleanField(default=False)),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('service_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hr.servicetype')),
            ],
            options={
                'db_table': 'hr_smart_pricing',
            },
        ),
    ]
