# Generated by Django 5.0.4 on 2025-11-02 04:20

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_smartpricing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smart_Pricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type_id', models.IntegerField(default=1)),
                ('hours_peak', models.BooleanField(default=False)),
                ('customer_history_score', models.PositiveIntegerField(default=0)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('base_rate', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('proposed_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accepted_status', models.BooleanField(default=False)),
                ('reward', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'hr_smartpricing',
            },
        ),
        migrations.DeleteModel(
            name='SmartPricing',
        ),
    ]
