# Generated by Django 5.0.4 on 2025-11-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_customer_img_smartpricing'),
        ('hr', '0011_alter_order_options_alter_order_customer_and_more'),
    ]

    operations = [
    ]
